### ISSUE TITLE
error bad public key x/y (leading zeros?)

### ISSUE THREAD

**Issue by ShaliDaliHaliDa** [reds/bitkeygen#1]
This is great thanks. I am trying to understand why I am getting x/y with 31 bytes instead of 32? Do we need to pad them?

if ( BN_num_bytes(x) != 32 ) {
    //    printf ( "error bad public key x (leading zeros?)\n" );
    //    exit ( 2 );
  }
  if ( BN_num_bytes(y) != 32 ) {
    //    printf ( "error bad public key y (leading zeros?)\n" );
    //    exit ( 2 );
  }

**Comment by reds** [comment]
Hi and thanks,

BN_num_bytes returns the position of the most significant 1 bit. I had assumed it returned the number of bytes used by the bignum. So in practice it was not a good test, I should remove it. Your x/y is 32 bytes in length but in some cases (because of leading zeros) the most significant 1 bit is not in the 32nd byte. In these cases BN_num_bytes is returning a value less than 32.

**Comment by ShaliDaliHaliDa** [comment]
Thanks for the explanation. I guess that makes sense, just somehow when it returns 31 bytes the resulting PublicAddress() appears to be incorrect. 

I tried padding x/y like so:

// Padding X example. Incorrect!
char *buffer = malloc((BN_num_bytes(x)) * sizeof(char));
BN_bn2bin(x, buffer);
BN_bin2bn(buffer, SHA256_DIGEST_LENGTH, x);
free(buffer);
 
I figured that will force X to be 32 bytes but that was incorrect. Any ideas how to fix it when the most significant 1 bit is not in the 32nd byte? Is it something obvious?

**Comment by ShaliDaliHaliDa** [comment]
Something weird going on. Some of the vanity addresses appear to be incorrect so I tested it with:

const unsigned char *pwd = "brainwallet";
size_t length;
length = strlen((const char *)pwd);
privdata = SHA256(pwd,length, 0);

BN_bin2bn ( privdata, SHA256_DIGEST_LENGTH, privkey );
pub = PublicAddress ( calcECPubkey ( group, x, y, privkey, scratch ), ctx, num, dv, rem );
printf("pub: %s\n",pub);

pub = 1NxgMMkqwcKFHWewYWk1zN648uPkhyxq5D   which is correct!

However, lets try pwd = “!$$u4ble”

and result is: error bad public key x (leading zeros?)

pub = 1LxJtHEMte2MFvyshSCWEk3hLyFoEpMtip which is incorrect! It should be “1DWVbedmBSMsxyFHo6pSSKxeYcQYNoAtJd”

Hence I figured we need to pad x/y accordingly?

**Comment by lianalancealot** [comment]
Good catch!! I tried "!$$u4ble" as privdata and the resulting pub is: 1LxJtHEMte2MFvyshSCWEk3hLyFoEpMtip

Checking at https://brainwallet.github.io/#generator it says that "!$$u4ble"  should be "1DWVbedmBSMsxyFHo6pSSKxeYcQYNoAtJd"

Bug?

**Comment by lianalancealot** [comment]
Interestingly "!$$u4bl" works but "!$$u4ble" is incorrect.

**Comment by reds** [comment]
Looks like you are right. I made a change that takes into account leading zeros in the x/y points.

**Comment by lianalancealot** [comment]
Awesome. That would rock.
